# Generated by Django 4.2 on 2024-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vendible', 'vendible'), ('no vendible', 'no vendible')], default='vendible', max_length=13)),
                ('name', models.CharField(max_length=255, verbose_name='Name of category')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('cocina', 'cocina'), ('bar', 'bar')], default='cocina', max_length=7)),
                ('name', models.CharField(max_length=255, verbose_name='Name of product')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost')),
                ('discount', models.FloatField(default=0.0, verbose_name='Discount')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='Image of product')),
                ('measure_unit', models.CharField(default='unidades', max_length=255, verbose_name='Measure unit')),
                ('categories', models.ManyToManyField(blank=True, to='productos.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
