# Generated by Django 4.2 on 2024-04-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_add_ingredient_stock_productingredientrelation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productaddrelation',
            options={'verbose_name': 'Relación de productos y agregados', 'verbose_name_plural': 'Relación de productos y agregados'},
        ),
        migrations.AlterModelOptions(
            name='productingredientrelation',
            options={'verbose_name': 'Relación de productos e ingredientes', 'verbose_name_plural': 'Relación de productos e ingredientes'},
        ),
        migrations.RemoveField(
            model_name='productingredientrelation',
            name='price',
        ),
    ]
