# Generated by Django 4.2 on 2024-04-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_category_active_alter_add_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='categories',
            field=models.ManyToManyField(blank=True, to='productos.category', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(blank=True, to='productos.category', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='productos.category', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='productaddrelation',
            name='add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_relations', to='productos.add', verbose_name='agregado'),
        ),
        migrations.AlterField(
            model_name='productaddrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_relations', to='productos.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='productingredientrelation',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_relations', to='productos.ingredient', verbose_name='ingrediente'),
        ),
        migrations.AlterField(
            model_name='productingredientrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_relations', to='productos.product', verbose_name='producto'),
        ),
    ]
