# Generated by Django 4.2 on 2024-04-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_add_categories_alter_ingredient_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='stock',
            field=models.ManyToManyField(to='productos.stock', verbose_name='almacenamiento stock'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.ManyToManyField(to='productos.stock', verbose_name='almacenamiento stock'),
        ),
    ]
