# Generated by Django 4.2 on 2024-04-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_add_stock_ingredient_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='measure_unit',
        ),
        migrations.AlterField(
            model_name='stock',
            name='measure_unit',
            field=models.CharField(choices=[('mililitros', 'mililitros'), ('gramos', 'gramos'), ('unidades', 'unidades')], default='unidades', max_length=13, verbose_name='tipo'),
        ),
    ]
