# Generated by Django 4.2 on 2024-04-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_add_measure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
        migrations.AlterField(
            model_name='stock',
            name='measure_unit',
            field=models.CharField(choices=[('mililitros', 'mililitros'), ('gramos', 'gramos'), ('unidades', 'unidades')], default='unidades', max_length=13, verbose_name='unidad de medida'),
        ),
        migrations.AddField(
            model_name='add',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.stock', verbose_name='almacenamiento stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='productos.stock', verbose_name='almacenamiento stock'),
            preserve_default=False,
        ),
    ]
