# Generated by Django 4.2 on 2024-05-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_stock_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='storage_threshold',
            field=models.PositiveIntegerField(default=100, verbose_name='umbral de stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio por unidad'),
        ),
    ]
