# Generated by Django 4.2 on 2024-05-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_stock_storage_threshold_stock_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Categoría de almacenamiento',
                'verbose_name_plural': 'Categorías de almacenamiento',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.stockcategory', verbose_name='Categoría de almacenamiento'),
        ),
    ]
