# Generated by Django 4.2 on 2024-05-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_stockcategory_stock_stock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
