# Generated by Django 4.2 on 2024-05-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('categories', models.ManyToManyField(blank=True, to='productos.category', verbose_name='categorias')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.stock', verbose_name='almacenamiento stock')),
            ],
            options={
                'verbose_name': 'Útil',
                'verbose_name_plural': 'Útiles',
            },
        ),
    ]
