# Generated by Django 4.2 on 2024-05-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_utilproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='price',
        ),
    ]
