# Generated by Django 4.2 on 2024-10-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_remove_add_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('cant', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
            ],
            options={
                'verbose_name': 'AFT',
                'verbose_name_plural': 'AFT',
            },
        ),
    ]
