# Generated by Django 4.2 on 2024-10-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_aft'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='almacenamiento en stock')),
                ('measure_unit', models.CharField(choices=[('mililitros', 'mililitros'), ('gramos', 'gramos'), ('unidades', 'unidades')], default='unidades', max_length=13, verbose_name='unidad de medida')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Próximo a vencer')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio por unidad')),
                ('storage_threshold', models.PositiveIntegerField(default=100, verbose_name='umbral de stock')),
                ('stock_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.stockcategory', verbose_name='Categoría de almacenamiento')),
            ],
            options={
                'verbose_name': 'Almacen Principal',
                'verbose_name_plural': 'Almacen Principal',
            },
        ),
    ]
