# Generated by Django 4.2 on 2024-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_principalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='place',
            field=models.CharField(choices=[('cocina', 'cocina'), ('bar', 'bar'), ('dependiente', 'dependiente')], default='cocina', max_length=11, verbose_name='lugar de elaboración'),
        ),
    ]
