# Generated by Django 4.2 on 2024-04-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_module_delete_moduls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
