# Generated by Django 4.2 on 2024-04-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0002_alter_table_delivered_alter_table_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0009_remove_add_stock_remove_ingredient_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.CharField(choices=[('pagada', 'pagada'), ('no pagada', 'no pagada')], default='no pagada', max_length=9, verbose_name='estado')),
                ('paid_method', models.CharField(choices=[('transferencia', 'transferencia'), ('efectivo', 'cash'), ('ambos', 'ambos')], default='efectivo', max_length=13, verbose_name='mótodo de pago')),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio total')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='dia de apertura')),
                ('created_time', models.TimeField(auto_now_add=True, null=True, verbose_name='hora de apertura')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.table', verbose_name='mesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ordenado', 'ordenado'), ('finalizado', 'finalizado'), ('entregado', 'entregado'), ('cancelado', 'cancelado')], default='ordenado', max_length=10)),
                ('cant', models.PositiveIntegerField(default=1, verbose_name='Cant')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.order', verbose_name='almacenamiento stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=1, verbose_name='Cant')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.add', verbose_name='agregado')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.item', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Agregado de pedido',
                'verbose_name_plural': 'Agregados de pedidos',
            },
        ),
    ]
