# Generated by Django 4.2 on 2024-04-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_barchartmodel_alter_item_order_alter_item_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarChartModel',
        ),
    ]
