# Generated by Django 4.2 on 2024-04-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_delete_barchartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Pagado por efectivo'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Pagado por transferencia'),
        ),
    ]
