# Generated by Django 4.2 on 2024-05-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_order_total_paid_order_cash_order_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('ordenado', 'ordenado'), ('preparando', 'preparando'), ('finalizado', 'finalizado'), ('entregado', 'entregado'), ('cancelado', 'cancelado')], default='ordenado', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_method',
            field=models.CharField(choices=[('transferencia', 'transferencia'), ('efectivo', 'efectivo'), ('ambos', 'ambos')], default='efectivo', max_length=13, verbose_name='mótodo de pago'),
        ),
    ]
