# Generated by Django 4.2 on 2024-05-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_item_state_alter_order_paid_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField(verbose_name='Fecha de inicio de turno')),
                ('in_time', models.TimeField(verbose_name='Hora de inicio de turno')),
                ('out_date', models.DateField(verbose_name='Fecha de fin de turno')),
                ('out_time', models.TimeField(verbose_name='Hora de fin de turno')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.shift', verbose_name='turno'),
        ),
    ]
