# Generated by Django 4.2 on 2024-05-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_shift_order_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
