# Generated by Django 4.2 on 2024-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_shift_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('llevar', 'llevar'), ('local', 'local')], default='local', max_length=7),
        ),
    ]
