# Generated by Django 4.2 on 2024-05-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_utilproduct'),
        ('cuentas', '0008_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=1, verbose_name='Cant')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.item', verbose_name='pedido')),
                ('util', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.utilproduct', verbose_name='útil')),
            ],
            options={
                'verbose_name': 'Útil de pedido',
                'verbose_name_plural': 'Útiles de pedidos',
            },
        ),
    ]
