# Generated by Django 4.2 on 2024-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_utilsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
