# Generated by Django 4.2 on 2024-05-26 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0010_shift_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_method',
            field=models.CharField(choices=[('transferencia', 'transferencia'), ('efectivo', 'efectivo'), ('ambos', 'ambos')], default='efectivo', max_length=13, verbose_name='método de pago'),
        ),
        migrations.CreateModel(
            name='CashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='ingreso', max_length=13, verbose_name='tipo de movimiento')),
                ('payment_type', models.CharField(choices=[('transferencia', 'transferencia'), ('efectivo', 'efectivo')], default='efectivo', max_length=13, verbose_name='método de pago')),
                ('ammount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='monto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='dia de registro')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.shift', verbose_name='turno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
            },
        ),
    ]
