# Generated by Django 4.2 on 2024-05-26 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0012_remove_cashoperation_ammount_cashoperation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoperation',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Día de registro'),
        ),
        migrations.AlterField(
            model_name='cashoperation',
            name='payment_type',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], default='efectivo', max_length=13, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='cashoperation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.shift', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='cashoperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
