# Generated by Django 4.2 on 2024-05-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_alter_cashoperation_shift_alter_cashoperation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cuentas.shift', verbose_name='turno'),
        ),
    ]
