# Generated by Django 4.2 on 2024-06-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_alter_order_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMotiveCancelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.TextField(blank=True, default='', null=True, verbose_name='Motivo')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.item', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
            },
        ),
    ]
