# Generated by Django 4.2 on 2024-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_itemmotivecancelmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
