# Generated by Django 4.2 on 2024-06-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0017_shift_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='revenue_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Revenue price'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Ganancia'),
        ),
    ]
