# Generated by Django 4.2 on 2024-09-08 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0018_item_revenue_price_alter_shift_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='ingreso', max_length=13, verbose_name='Tipo de movimiento')),
                ('payment_type', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], default='efectivo', max_length=13, verbose_name='Método de pago')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Día de registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_operation', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Operacione',
                'verbose_name_plural': 'Operaciones',
            },
        ),
    ]
