# Generated by Django 4.2 on 2024-09-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0020_operation_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
