# Generated by Django 4.2 on 2024-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0022_item_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
