# Generated by Django 4.2 on 2024-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0024_item_created_time_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='hora de inicio'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='hora de finalización'),
        ),
    ]
