# Generated by Django 4.2 on 2024-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0025_alter_item_created_time_alter_item_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de clientes'),
        ),
    ]
