# Generated by Django 4.2 on 2024-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0027_alter_order_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customers',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de clientes'),
        ),
    ]
