# Generated by Django 4.2 on 2024-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0030_ingredientitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
    ]
