# Generated by Django 4.2 on 2024-04-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=True, verbose_name='entrega rápida')),
                ('state', models.CharField(choices=[('ocupada', 'ocupada'), ('libre', 'libre')], default='libre', max_length=7, verbose_name='estado')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
    ]
