# Generated by Django 4.2 on 2024-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='entrega rápida'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nombre'),
        ),
    ]
