# Generated by Django 4.2 on 2025-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_table_delivered_alter_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='customer_cant',
            field=models.PositiveIntegerField(default=2, verbose_name='aproximado de clientes'),
        ),
    ]
