# Generated by Django 4.2 on 2024-06-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Exchange rate'},
        ),
    ]
