# Generated by Django 4.2 on 2024-06-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Tasa de cambio'},
        ),
        migrations.AddField(
            model_name='coin',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor de un dólar en CUP:'),
        ),
    ]
