# Generated by Django 4.2 on 2024-06-19 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_coin_options_coin_active_alter_coin_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Valor de un dólar en CUP:'),
        ),
    ]
