# Generated by Django 4.2 on 2024-04-24 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0007_add_stock_ingredient_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salida', 'salida'), ('entrada', 'entrada')], default='entrada', max_length=7, verbose_name='tipo')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('created_time', models.TimeField(auto_now_add=True, null=True, verbose_name='hora de creación')),
                ('motive', models.CharField(choices=[('reabastecer', 'reabastecer'), ('perdida', 'perdida'), ('cancelado', 'cancelado'), ('error', 'error'), ('otro', 'otro')], default='reabastecer', max_length=11, verbose_name='motivo')),
                ('message', models.TextField(blank=True, null=True, verbose_name='detalle')),
                ('cant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='monto')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.stock', verbose_name='almacenamiento stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
