# Generated by Django 4.2 on 2024-04-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_alter_stockmovements_cant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovements',
            name='motive',
            field=models.CharField(choices=[('reabastecer', 'reabastecer'), ('pérdida', 'pérdida'), ('cancelado', 'cancelado'), ('error', 'error'), ('otro', 'otro')], default='reabastecer', max_length=11, verbose_name='motivo'),
        ),
    ]
