# Generated by Django 4.2 on 2024-04-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_alter_stockmovements_motive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovements',
            options={'verbose_name': 'Movimiento en almacen', 'verbose_name_plural': 'Movimientos en stock'},
        ),
    ]
