# Generated by Django 4.2 on 2024-12-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_alter_stockmovements_cant_principalstockmovements'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStockMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en ese momento')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por unidad en ese momento')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.stockmovements', verbose_name='stock_movements')),
            ],
            options={
                'verbose_name': 'Historico de movimiento en almacen',
                'verbose_name_plural': 'Historicos de movimiento en stock',
            },
        ),
    ]
